import Link from 'next/link';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'شرکت مهندسی سامانه های پشتیبان تصمیم، تاک​​​​​​​​بن',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={inter.className}>
        <nav>
          <ul>
            <li><Link href="/"></Link></li>
            {/* <li><Link href="/Admin"> </Link></li> */}
            <li><Link href='/Admin/login'> </Link></li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
